import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from 'components/Navbar';
import ArticlesSection from 'components/ArticlesSection';
import CheckAuth from '@/components/CheckAuth';


const Home: NextPage = () => {

  return (
    <div>
      <CheckAuth />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
            integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
            crossOrigin="anonymous"
        />

      </Head>

      <div className="flex flex-col">
        <Navbar/>
        <ArticlesSection />
      </div>

    </div>
  )
}

export default Home
